# -*- coding: utf-8 -*-
"""ADS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y8GJkhsTlmI6FaJXEZWagoxpToWnTJMX
"""

# To upload Files in Google Drive.. 

from google.colab import files


uploaded = files.upload()

# https://medium.com/mlearning-ai/univariate-bivariate-and-multivariate-data-analysis-in-python-341493c3d173

# Commented out IPython magic to ensure Python compatibility.
# Univariate Analysis

'''  
Uni means one, univariate analysis means the analysis of 
one variable ata time.
univariate is a common term that we use in statistics to describe a type of 
chart that contains only one attribute or or characterstic.
'''
# Importing Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns
import math
import io

df = pd.read_csv(io.BytesIO(uploaded['House Price India.csv']))
df.info()

df.head()

# To find the duplications in the rows
df.duplicated().sum()

''' 
Categorical data : type of data that represents qualitative or descriptive 
characteristics of a sample 
Continuous data : ype of numerical data that can take on any value within a 
specific range or interval
'''
# Start with Continuous data

#By using the describe function on the selected columns, we get the mean, 
# std, min, max, 25th percentile, 50th percentile, and 75% percentile values
# of the columns.

df[['number of bedrooms','number of bathrooms','living area',
    'lot area','number of floors','Area of the house(excluding basement)',
    'Area of the basement','living_area_renov','lot_area_renov',
    'Number of schools nearby',
    'Distance from the airport','Price']].describe()

# sns.histplot(df.bed,kde=True)
sns.histplot(data=df, x='Price', bins=20,kde=True)
plt.show()

#Univariate Analysis of Categorical Variables
# Categorical data  : waterfront present, number of views, condition of house, grade of the house
sns.countplot(data=df, x='grade of the house')
# sns.countplot(data=df, x='number of views')
plt.show()

# Bivariate analysis
'''
Bivariate analysis is slightly more analytical than Univariate analysis.
comparisons between the two dataset.
The first step in performing bivariate analysis
 between continuous variables would be to calculate correlations between them
'''
df[[
    'Distance from the airport','Price',
    'number of floors','Area of the house(excluding basement)',
    'Area of the basement',]].corr()

sns.scatterplot(y='Price', x='Area of the house(excluding basement)', data=df)

# Multivariate analysis
'''
Multivariate analysis is a more complex form of a statistical
analysis technique and is used when there are more than two variables
in the data set.
'''
sns.pairplot(data=df[['Distance from the airport','Price',
    'Area of the house(excluding basement)',
    'Area of the basement',]],hue='Price')

# Descriptive Statistics

'''
A raw dataset is difficult to describe; descriptive statistics describe the 
dataset in a way simpler manner.
there are three main fundamental concepts associated with describing the data:
location or Central tendency, Dissemination or spread, and Shape or distribution
'''
# Mean

df.mean()

# Median
df.median()

# Mode
df.mode()

# Summarising Data
df.describe(include='all')

# Handlinig missing values
'''
ffill
bfill
'''
df2 = df.fillna(method='ffill')
df2



